# -*- coding: utf-8 -*-
"""HiNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pq1ByA0Ia7Cx7r0nXN_9_3MGTPTKEZb
"""

!git clone https://github.com/TomTomTommi/HiNet.git

!pip install -r /content/requirements.txt

!pip install -q tensorboardX

"""## Adding kaggle image net dataset to colab"""

!pip install -q kaggle

from google.colab import files
files.upload()  # Upload kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!ls ~/.kaggle

!mkdir /content/imagenet/

#!/bin/bash
!curl -L -o /content/imagenet/dataset.zip \
  https://www.kaggle.com/api/v1/datasets/download/abhinav1609/steganography-imagenet

!unzip -q /content/imagenet/dataset.zip -d /content/imagenet

!mkdir /content/output/model/

!mkdir /content/output/image/

import torch
torch.cuda.empty_cache()

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

!python train.py